---
layout: post
title: "Python 3.5 and Django 1.7's HTMLParseError"
date: 2015-02-15T13:20:00+05:30
tags:
 - Python
 - Django
---

<div class='post'>
<div dir="ltr" style="text-align: left;" trbidi="on">I just updated my Python installation to 3.5 Alpha 1 and started with Django today and I hit a road block already. It all went fine, when I created the virtual environment and installed Django 1.7.4 in it. And then when I did <code>startproject</code>, I got <code>AttributeError: module 'html.parser' has no attribute 'HTMLParseError'</code>.<br /><pre class="prettyprint">(py3.5venv) ➜  myProject git:(master) ✗ django-admin.py startproject myProject<br />Traceback (most recent call last):<br />  File "/py3.5venv/bin/django-admin.py", line 5, in <module><br />    management.execute_from_command_line()<br />  File "/py3.5venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line<br />    utility.execute()<br />  File "/py3.5venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute<br />    django.setup()<br />  File "/py3.5venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup<br />    from django.utils.log import configure_logging<br />  File "/py3.5venv/lib/python3.5/site-packages/django/utils/log.py", line 13, in <module><br />    from django.views.debug import ExceptionReporter, get_exception_reporter_filter<br />  File "/py3.5venv/lib/python3.5/site-packages/django/views/debug.py", line 10, in <module><br />    from django.http import (HttpResponse, HttpResponseServerError,<br />  File "/py3.5venv/lib/python3.5/site-packages/django/http/__init__.py", line 4, in <module><br />    from django.http.response import (<br />  File "/py3.5venv/lib/python3.5/site-packages/django/http/response.py", line 13, in <module><br />    from django.core.serializers.json import DjangoJSONEncoder<br />  File "/py3.5venv/lib/python3.5/site-packages/django/core/serializers/__init__.py", line 23, in <module><br />    from django.core.serializers.base import SerializerDoesNotExist<br />  File "/py3.5venv/lib/python3.5/site-packages/django/core/serializers/base.py", line 6, in <module><br />    from django.db import models<br />  File "/py3.5venv/lib/python3.5/site-packages/django/db/models/__init__.py", line 6, in <module><br />    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA<br />  File "/py3.5venv/lib/python3.5/site-packages/django/db/models/query.py", line 13, in <module><br />    from django.db.models.fields import AutoField, Empty<br />  File "/py3.5venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 18, in <module><br />    from django import forms<br />  File "/py3.5venv/lib/python3.5/site-packages/django/forms/__init__.py", line 6, in <module><br />    from django.forms.fields import *  # NOQA<br />  File "/py3.5venv/lib/python3.5/site-packages/django/forms/fields.py", line 18, in <module><br />    from django.forms.utils import from_current_timezone, to_current_timezone<br />  File "/py3.5venv/lib/python3.5/site-packages/django/forms/utils.py", line 15, in <module><br />    from django.utils.html import format_html, format_html_join, escape<br />  File "/py3.5venv/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module><br />    from .html_parser import HTMLParser, HTMLParseError<br />  File "/py3.5venv/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module><br />    HTMLParseError = _html_parser.HTMLParseError<br />AttributeError: module 'html.parser' has no attribute 'HTMLParseError'</pre>Then <a href="http://stackoverflow.com/users/918959/antti-haapala">Antti Haapala</a> (a friend from <a href="http://chat.stackoverflow.com/rooms/6/python">Stakoverflow's Python Chat room</a>) found out that it is because <code class="prettyprint">HTMLParseError</code> is deprecated from Python 3.3 onwards and removed in Python 3.5, as per the <a href="https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParseError">official documentation</a>. He continued the investigation and found out that django guys are already aware of this, as they have <a href="https://code.djangoproject.com/ticket/23763">a bug raised</a>, and <a href="https://github.com/django/django/commit/b07aa52e8a8e4c7fdc7265f75ce2e7992e657ae9">the fix has been already delivered</a> to the code repository.<br />Now, all we can do is, wait for the version of django which officially supports Python 3.5 or manually patch html_parser.py file as per the above shown fix. Even if we patch it manually, there is no guarantee that everything else will work fine.<br /></div></div>
